/*
 * generated by Xtext 2.11.0
 */
package org.franca.compdeploymodel.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CDeployStandaloneSetup extends CDeployStandaloneSetupGenerated {

	def static void doSetup() {
		new CDeployStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
